name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '28 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node generate-readme.js
        env:
          LEVELS_DB_URL: ${{ secrets.LEVELS_DB_URL }}

      - name: Push the README changes
        uses: EndBug/add-and-commit@v7